[package]
name = "oes-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "oes"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
oes-config = { path = "../../crates/oes-config" }
oes-core = { path = "../../crates/oes-core" }
oes-observability = { path = "../../crates/oes-observability" }
oes-server = { path = "../oes-server" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
