[package]
name = "oes-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
chrono.workspace = true
futures-util.workspace = true
oes-core = { path = "../oes-core" }
oes-events = { path = "../oes-events" }
oes-metadata = { path = "../oes-metadata" }
oes-storage = { path = "../oes-storage" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
