[package]
name = "record-store-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
chrono.workspace = true
futures-util.workspace = true
record-store-core = { path = "../record-store-core" }
record-store-audit = { path = "../record-store-audit" }
record-store-events = { path = "../record-store-events" }
record-store-metadata = { path = "../record-store-metadata" }
record-store-storage = { path = "../record-store-storage" }
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[dev-dependencies]
async-trait.workspace = true
tempfile.workspace = true

[lints]
workspace = true
