[package]
name = "record-store-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
aes-gcm.workspace = true
async-trait.workspace = true
bytes.workspace = true
chrono.workspace = true
futures-core.workspace = true
futures-util.workspace = true
fs2.workspace = true
hex.workspace = true
hkdf.workspace = true
md-5.workspace = true
record-store-core = { path = "../record-store-core" }
record-store-metadata = { path = "../record-store-metadata" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true
zeroize.workspace = true

[dev-dependencies]
criterion.workspace = true
tempfile.workspace = true

[[bench]]
name = "storage"
harness = false

[lints]
workspace = true
