use serde::{Deserialize, Serialize};

use crate::*;

/// Validated zero-based index of a shard within one erasure stripe.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(try_from = "u16", into = "u16")]
pub struct ShardIndex(u16);

impl ShardIndex {
    /// Record Store deliberately keeps initial profiles small enough for one shard per node.
    pub const MAX: u16 = 31;

    /// Creates a shard index within the supported on-disk format.
    pub fn new(value: u16) -> Result<Self, CoreError> {
        if value <= Self::MAX {
            Ok(Self(value))
        } else {
            Err(CoreError::InvalidErasureProfile(format!(
                "shard index must be between 0 and {}",
                Self::MAX
            )))
        }
    }

    /// Returns the zero-based numeric index.
    #[must_use]
    pub const fn get(self) -> u16 {
        self.0
    }
}

impl TryFrom<u16> for ShardIndex {
    type Error = CoreError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        Self::new(value)
    }
}

impl From<ShardIndex> for u16 {
    fn from(value: ShardIndex) -> Self {
        value.get()
    }
}

/// Role of one shard in a systematic Reed-Solomon stripe.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ShardKind {
    /// A systematic shard that contains original object bytes.
    Data,
    /// A recovery shard generated by the codec.
    Parity,
}

/// Persisted lifecycle and integrity state of one erasure shard.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ShardState {
    /// Bytes are being staged and cannot be used.
    Pending,
    /// Bytes were independently checksummed and committed.
    Healthy,
    /// Reconstruction is in progress.
    Repairing,
    /// The shard is absent from its committed placement.
    Missing,
    /// Stored bytes failed their committed checksum.
    Corrupt,
    /// The shard is known to be permanently unrecoverable.
    Unrecoverable,
    /// The shard is being retired.
    Deleting,
}

impl ShardState {
    /// Returns whether this shard can count toward reconstruction.
    #[must_use]
    pub const fn readable(self) -> bool {
        matches!(self, Self::Healthy)
    }

    /// Returns whether this shard counts toward committed durability.
    #[must_use]
    pub const fn durable(self) -> bool {
        matches!(self, Self::Healthy)
    }
}
