[package]
name = "oes-lifecycle"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
oes-audit = { path = "../oes-audit" }
oes-core = { path = "../oes-core" }
oes-metadata = { path = "../oes-metadata" }
oes-service = { path = "../oes-service" }
redb.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[dev-dependencies]
oes-storage = { path = "../oes-storage" }
tempfile.workspace = true

[lints]
workspace = true
