[package]
name = "oes-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
prost.workspace = true
tonic.workspace = true

[build-dependencies]
prost-build = "0.13.5"
protoc-bin-vendored.workspace = true
tonic-build.workspace = true

[lints]
workspace = true

