[package]
name = "record-store-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
hex.workspace = true
redb.workspace = true
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
proptest.workspace = true
serde_json.workspace = true
redb-v2.workspace = true
tempfile.workspace = true

[lints]
workspace = true
