[package]
name = "oes-replication"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
chrono.workspace = true
futures-util.workspace = true
hex.workspace = true
md-5.workspace = true
oes-audit = { path = "../oes-audit" }
oes-cluster = { path = "../oes-cluster" }
oes-consensus = { path = "../oes-consensus" }
oes-core = { path = "../oes-core" }
oes-metadata = { path = "../oes-metadata" }
oes-protocol = { path = "../oes-protocol" }
oes-rpc = { path = "../oes-rpc" }
oes-storage = { path = "../oes-storage" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
